version: '2'
services:
  reverse-proxy-1:
    network_mode: "host"
    image: "proxy2"
    container_name: test-reverse-proxy
    ports:
      - "80:80"
    restart: always
    tty: true
    stdin_open: true
  nodejs1:
    network_mode: "host"
    image: "node-app1"
    container_name: nodejs1
    ports:
      - "3000:3000"
    restart: always
    tty: true
    stdin_open: true
  python1:
    network_mode: "host"
    image: "python1"
    container_name: python-app
    ports:
      - "5000:5000"
    restart: always
    tty: true
    stdin_open: true
